import { User, Ride, CommunityEvent } from "@/types";
import { Timestamp } from "firebase/firestore";

const now = Timestamp.now();

export const MOCK_USERS: User[] = [
  {
    id: "user1",
    email: "nico@unc.edu",
    name: "Nico Garcia",
    photoUrl: "/avatars/nico.jpg",
    address: { address: "123 Franklin St, Chapel Hill, NC", lat: 35.9132, lng: -79.0558 },
    major: "Business Administration",
    status: "student",
    interests: ["fintech", "basketball", "entrepreneurship"],
    vibe: "chatty",
    clubs: ["Entrepreneurship Club", "Intramural Sports"],
    car: {
      driversLicenseUrl: "/licenses/nico.jpg",
      brand: "Toyota",
      model: "Corolla",
      color: "Gray",
      licensePlate: "ABC-1234",
    },
    stats: {
      totalRides: 24,
      totalKm: 312,
      co2Saved: 65.5,
      peopleConnected: 8,
      averageRating: 4.8,
      averageGoodVibes: 4.6,
      totalRatings: 18,
    },
    badges: [
      {
        id: "icebreaker",
        name: "Icebreaker",
        description: "First ride with someone new",
        icon: "🧊",
        unlockedAt: now,
      },
      {
        id: "eco-hero",
        name: "Eco Hero",
        description: "Saved more than 50 kg CO2",
        icon: "🌱",
        unlockedAt: now,
      },
      {
        id: "punctual",
        name: "Punctual",
        description: "Always on time",
        icon: "⏰",
        unlockedAt: now,
      },
    ],
    connections: ["user2", "user3"],
    createdAt: now,
  },
  {
    id: "user2",
    email: "tomi@unc.edu",
    name: "Tomi Lopez",
    photoUrl: "/avatars/tomi.jpg",
    address: { address: "300 E Main St, Carrboro, NC", lat: 35.9101, lng: -79.0753 },
    major: "Computer Science",
    status: "student",
    interests: ["technology", "running", "movies"],
    vibe: "podcast_listener",
    clubs: ["Tar Heel Esports", "Carolina Club Running"],
    car: {
      driversLicenseUrl: "/licenses/tomi.jpg",
      brand: "Chevrolet",
      model: "Malibu",
      color: "White",
      licensePlate: "EFG-5678",
    },
    stats: {
      totalRides: 15,
      totalKm: 180,
      co2Saved: 37.8,
      peopleConnected: 5,
      averageRating: 4.6,
      averageGoodVibes: 4.3,
      totalRatings: 12,
    },
    badges: [
      {
        id: "icebreaker",
        name: "Icebreaker",
        description: "First ride with someone new",
        icon: "🧊",
        unlockedAt: now,
      },
    ],
    connections: ["user1", "user3"],
    createdAt: now,
  },
  {
    id: "user3",
    email: "belu@unc.edu",
    name: "Belu Martinez",
    photoUrl: "/avatars/belu.jpg",
    address: { address: "456 W Chapel Hill St, Durham, NC", lat: 35.9940, lng: -78.9106 },
    major: "Economics",
    status: "student",
    interests: ["yoga", "travel", "reading"],
    vibe: "chill",
    clubs: ["Carolina Outdoors", "Volunteer Corps"],
    stats: {
      totalRides: 10,
      totalKm: 95,
      co2Saved: 19.9,
      peopleConnected: 4,
      averageRating: 4.9,
      averageGoodVibes: 4.8,
      totalRatings: 8,
    },
    badges: [
      {
        id: "icebreaker",
        name: "Icebreaker",
        description: "First ride with someone new",
        icon: "🧊",
        unlockedAt: now,
      },
      {
        id: "explorer",
        name: "Explorer",
        description: "Rode with people from 5 different majors",
        icon: "🧭",
        unlockedAt: now,
      },
    ],
    connections: ["user1", "user2"],
    createdAt: now,
  },
  {
    id: "user4",
    email: "flor@unc.edu",
    name: "Flor Russo",
    photoUrl: "/avatars/flor.jpg",
    address: { address: "200 S Churton St, Hillsborough, NC", lat: 36.0726, lng: -79.0992 },
    major: "Communications",
    status: "student",
    interests: ["art", "music", "photography"],
    vibe: "music_lover",
    clubs: ["Photography Club", "Music Makers"],
    stats: {
      totalRides: 6,
      totalKm: 42,
      co2Saved: 8.8,
      peopleConnected: 3,
      averageRating: 5.0,
      averageGoodVibes: 4.9,
      totalRatings: 5,
    },
    badges: [],
    connections: [],
    createdAt: now,
  },
  {
    id: "user5",
    email: "demo@unc.edu",
    name: "Martin Perez",
    photoUrl: "/avatars/demo.jpg",
    address: { address: "500 Estes Dr, Chapel Hill, NC", lat: 35.9280, lng: -79.0400 },
    major: "Political Science",
    status: "student",
    interests: ["basketball", "politics"],
    vibe: "chatty",
    clubs: ["Debate Society", "UNC Club Soccer"],
    stats: {
      totalRides: 0,
      totalKm: 0,
      co2Saved: 0,
      peopleConnected: 0,
      averageRating: 0,
      averageGoodVibes: 0,
      totalRatings: 0,
    },
    badges: [],
    connections: [],
    createdAt: now,
  },
  {
    id: "user6",
    email: "sofi@unc.edu",
    name: "Sofi Fernandez",
    photoUrl: "/avatars/demo2.jpg",
    address: { address: "800 W Main St, Durham, NC", lat: 35.9940, lng: -78.9106 },
    major: "Business Administration",
    status: "student",
    interests: ["fintech", "startups"],
    vibe: "study_mode",
    clubs: ["Entrepreneurship Club", "Women in CS"],
    car: {
      driversLicenseUrl: "/licenses/sofi.jpg",
      brand: "VW",
      model: "Golf",
      color: "Black",
      licensePlate: "HIJ-9012",
    },
    stats: {
      totalRides: 18,
      totalKm: 290,
      co2Saved: 60.9,
      peopleConnected: 7,
      averageRating: 4.7,
      averageGoodVibes: 4.5,
      totalRatings: 14,
    },
    badges: [
      {
        id: "icebreaker",
        name: "Icebreaker",
        description: "First ride with someone new",
        icon: "🧊",
        unlockedAt: now,
      },
      {
        id: "eco-hero",
        name: "Eco Hero",
        description: "Saved more than 50 kg CO2",
        icon: "🌱",
        unlockedAt: now,
      },
    ],
    connections: ["user1"],
    createdAt: now,
  },
];

export const MOCK_RIDES: Ride[] = [
  {
    id: "ride1",
    driverId: "user1",
    driverName: "Nico Garcia",
    driverPhotoUrl: "/avatars/nico.jpg",
    driverMajor: "Business Administration",
    driverRating: 4.8,
    driverVibe: "chatty",
    driverCar: {
      driversLicenseUrl: "/licenses/nico.jpg",
      brand: "Toyota",
      model: "Corolla",
      color: "Gray",
      licensePlate: "ABC-1234",
    },
    origin: {
      address: "123 Franklin St, Chapel Hill, NC",
      lat: 35.9132,
      lng: -79.0558,
    },
    destination: {
      address: "UNC Chapel Hill, South Rd, Chapel Hill, NC",
      lat: 35.9049,
      lng: -79.0469,
    },
    departureTimeStart: "2026-04-10T18:00",
    departureTimeEnd: "2026-04-10T18:30",
    totalSeats: 3,
    availableSeats: 2,
    pickupFlexibility: "flexible",
    flexibleRadiusMi: 2,
    eventId: "event1",
    eventName: "UNC vs Duke Basketball",
    note: "Driving through Carrboro, trunk space available",
    status: "active",
    passengers: [],
    ratings: [],
    createdAt: now,
  },
  {
    id: "ride2",
    driverId: "user2",
    driverName: "Tomi Lopez",
    driverPhotoUrl: "/avatars/tomi.jpg",
    driverMajor: "Computer Science",
    driverRating: 4.6,
    driverVibe: "podcast_listener",
    driverCar: {
      driversLicenseUrl: "/licenses/tomi.jpg",
      brand: "Chevrolet",
      model: "Malibu",
      color: "White",
      licensePlate: "EFG-5678",
    },
    origin: {
      address: "300 E Main St, Carrboro, NC",
      lat: 35.9101,
      lng: -79.0753,
    },
    destination: {
      address: "UNC Chapel Hill, South Rd, Chapel Hill, NC",
      lat: 35.9049,
      lng: -79.0469,
    },
    departureTimeStart: "2026-04-12T17:00",
    departureTimeEnd: "2026-04-12T17:30",
    totalSeats: 2,
    availableSeats: 2,
    pickupFlexibility: "fixed",
    eventId: "event2",
    eventName: "CS Alumni Networking Night",
    status: "active",
    passengers: [],
    ratings: [],
    createdAt: now,
  },
  {
    id: "ride3",
    driverId: "user6",
    driverName: "Sofi Fernandez",
    driverPhotoUrl: "/avatars/demo2.jpg",
    driverMajor: "Business Administration",
    driverRating: 4.7,
    driverVibe: "study_mode",
    driverCar: {
      driversLicenseUrl: "/licenses/sofi.jpg",
      brand: "VW",
      model: "Golf",
      color: "Black",
      licensePlate: "HIJ-9012",
    },
    origin: {
      address: "800 W Main St, Durham, NC",
      lat: 35.9940,
      lng: -78.9106,
    },
    destination: {
      address: "UNC Chapel Hill, South Rd, Chapel Hill, NC",
      lat: 35.9049,
      lng: -79.0469,
    },
    departureTimeStart: "2026-03-30T07:45",
    departureTimeEnd: "2026-03-30T08:15",
    totalSeats: 3,
    availableSeats: 3,
    pickupFlexibility: "flexible",
    flexibleRadiusMi: 5,
    note: "Quiet ride, leaving early",
    status: "active",
    passengers: [],
    ratings: [],
    createdAt: now,
  },
  {
    id: "ride4",
    driverId: "user6",
    driverName: "Sofi Fernandez",
    driverPhotoUrl: "/avatars/demo2.jpg",
    driverMajor: "Business Administration",
    driverRating: 4.7,
    driverVibe: "music_lover",
    driverCar: {
      driversLicenseUrl: "/licenses/sofi.jpg",
      brand: "VW",
      model: "Golf",
      color: "Black",
      licensePlate: "HIJ-9012",
    },
    origin: {
      address: "800 W Main St, Durham, NC",
      lat: 35.9940,
      lng: -78.9106,
    },
    destination: {
      address: "Polk Place, UNC Campus, Chapel Hill, NC",
      lat: 35.9119,
      lng: -79.0510,
    },
    departureTimeStart: "2026-04-15T14:30",
    departureTimeEnd: "2026-04-15T15:00",
    totalSeats: 3,
    availableSeats: 3,
    pickupFlexibility: "flexible",
    flexibleRadiusMi: 5,
    eventId: "event3",
    eventName: "Spring Concert — Campus Green",
    note: "Let's start the concert vibes early 🎶",
    status: "active",
    passengers: [],
    ratings: [],
    createdAt: now,
  },
];

export const MOCK_EVENTS: CommunityEvent[] = [
  {
    id: "event1",
    name: "UNC vs Duke Basketball",
    description: "The rivalry game of the year",
    date: "2026-04-10",
    time: "19:00",
    location: {
      address: "Dean E. Smith Center, Chapel Hill, NC",
      lat: 35.9100,
      lng: -79.0478,
    },
    // Context doc §14: 15 interested. Real users listed first (shown as avatars in detail
    // page). Placeholder IDs pad the count — getUsersByIds skips unknowns, .length drives display.
    interestedUsers: ["user1", "user2", "user3", "p01", "p02", "p03", "p04", "p05", "p06", "p07", "p08", "p09", "p10", "p11", "p12"],
    createdAt: now,
  },
  {
    id: "event2",
    name: "CS Alumni Networking Night",
    description: "Meet alumni working in tech",
    date: "2026-04-12",
    time: "18:00",
    location: {
      address: "Sitterson Hall, UNC Campus",
      lat: 35.9105,
      lng: -79.0530,
    },
    // Context doc §14: 8 interested.
    interestedUsers: ["user1", "user4", "p01", "p02", "p03", "p04", "p05", "p06"],
    createdAt: now,
  },
  {
    id: "event3",
    name: "Spring Concert — Campus Green",
    description: "Live music on the quad",
    date: "2026-04-15",
    time: "16:00",
    location: {
      address: "Polk Place, UNC Campus",
      lat: 35.9119,
      lng: -79.0510,
    },
    // Context doc §14: 22 interested.
    interestedUsers: ["user2", "user3", "user5", "p01", "p02", "p03", "p04", "p05", "p06", "p07", "p08", "p09", "p10", "p11", "p12", "p13", "p14", "p15", "p16", "p17", "p18", "p19"],
    createdAt: now,
  },
];
