import { User, Ride } from "@/types";
import { Timestamp } from "firebase/firestore";

const now = Timestamp.now();

export const MOCK_USERS: User[] = [
  {
    id: "user1",
    email: "nico@utdt.edu",
    name: "Nico García",
    photoUrl: "/avatars/nico.jpg",
    department: "MBA",
    neighborhood: "Núñez",
    interests: ["fintech", "fútbol", "emprendimiento"],
    car: {
      brand: "Toyota",
      model: "Corolla",
      color: "Gris",
      licensePlate: "AB 123 CD",
    },
    stats: {
      totalRides: 24,
      totalKm: 312,
      co2Saved: 65.5,
      peopleConnected: 8,
      averageRating: 4.8,
      averageBuenaOnda: 4.6,
      totalRatings: 18,
    },
    badges: [
      {
        id: "rompehielo",
        name: "Rompehielo",
        description: "Primer viaje con alguien nuevo",
        icon: "🧊",
        unlockedAt: now,
      },
      {
        id: "eco-hero",
        name: "Eco-hero",
        description: "Ahorraste más de 50 kg CO2",
        icon: "🌱",
        unlockedAt: now,
      },
      {
        id: "puntual",
        name: "Puntual",
        description: "Siempre a tiempo",
        icon: "⏰",
        unlockedAt: now,
      },
    ],
    connections: ["user2", "user3"],
    createdAt: now,
  },
  {
    id: "user2",
    email: "tomi@utdt.edu",
    name: "Tomi López",
    photoUrl: "/avatars/tomi.jpg",
    department: "Negocios Digitales",
    neighborhood: "Belgrano",
    interests: ["tecnología", "running", "cine"],
    car: {
      brand: "Chevrolet",
      model: "Onix",
      color: "Blanco",
      licensePlate: "EF 456 GH",
    },
    stats: {
      totalRides: 15,
      totalKm: 180,
      co2Saved: 37.8,
      peopleConnected: 5,
      averageRating: 4.6,
      averageBuenaOnda: 4.3,
      totalRatings: 12,
    },
    badges: [
      {
        id: "rompehielo",
        name: "Rompehielo",
        description: "Primer viaje con alguien nuevo",
        icon: "🧊",
        unlockedAt: now,
      },
    ],
    connections: ["user1", "user3"],
    createdAt: now,
  },
  {
    id: "user3",
    email: "belu@utdt.edu",
    name: "Belu Martínez",
    photoUrl: "/avatars/belu.jpg",
    department: "Economía",
    neighborhood: "Vicente López",
    interests: ["yoga", "viajes", "lectura"],
    stats: {
      totalRides: 10,
      totalKm: 95,
      co2Saved: 19.9,
      peopleConnected: 4,
      averageRating: 4.9,
      averageBuenaOnda: 4.8,
      totalRatings: 8,
    },
    badges: [
      {
        id: "rompehielo",
        name: "Rompehielo",
        description: "Primer viaje con alguien nuevo",
        icon: "🧊",
        unlockedAt: now,
      },
      {
        id: "exploradora",
        name: "Exploradora",
        description: "Viajó con gente de 5 departamentos distintos",
        icon: "🧭",
        unlockedAt: now,
      },
    ],
    connections: ["user1", "user2"],
    createdAt: now,
  },
  {
    id: "user4",
    email: "flor@utdt.edu",
    name: "Flor Russo",
    photoUrl: "/avatars/flor.jpg",
    department: "Diseño",
    neighborhood: "Palermo",
    interests: ["arte", "música", "fotografía"],
    stats: {
      totalRides: 6,
      totalKm: 42,
      co2Saved: 8.8,
      peopleConnected: 3,
      averageRating: 5.0,
      averageBuenaOnda: 4.9,
      totalRatings: 5,
    },
    badges: [],
    connections: [],
    createdAt: now,
  },
  {
    id: "user5",
    email: "demo@utdt.edu",
    name: "Martín Pérez",
    photoUrl: "/avatars/demo.jpg",
    department: "Derecho",
    neighborhood: "Recoleta",
    interests: ["fútbol", "política"],
    stats: {
      totalRides: 0,
      totalKm: 0,
      co2Saved: 0,
      peopleConnected: 0,
      averageRating: 0,
      averageBuenaOnda: 0,
      totalRatings: 0,
    },
    badges: [],
    connections: [],
    createdAt: now,
  },
  {
    id: "user6",
    email: "demo2@utdt.edu",
    name: "Sofi Fernández",
    photoUrl: "/avatars/demo2.jpg",
    department: "MBA",
    neighborhood: "San Isidro",
    interests: ["fintech", "startups"],
    car: {
      brand: "VW",
      model: "Golf",
      color: "Negro",
      licensePlate: "IJ 789 KL",
    },
    stats: {
      totalRides: 18,
      totalKm: 290,
      co2Saved: 60.9,
      peopleConnected: 7,
      averageRating: 4.7,
      averageBuenaOnda: 4.5,
      totalRatings: 14,
    },
    badges: [
      {
        id: "rompehielo",
        name: "Rompehielo",
        description: "Primer viaje con alguien nuevo",
        icon: "🧊",
        unlockedAt: now,
      },
      {
        id: "eco-hero",
        name: "Eco-hero",
        description: "Ahorraste más de 50 kg CO2",
        icon: "🌱",
        unlockedAt: now,
      },
    ],
    connections: ["user1"],
    createdAt: now,
  },
];

export const MOCK_RIDES: Ride[] = [
  {
    id: "ride1",
    driverId: "user1",
    driverName: "Nico García",
    driverPhotoUrl: "/avatars/nico.jpg",
    driverDepartment: "MBA",
    driverRating: 4.8,
    driverCar: {
      brand: "Toyota",
      model: "Corolla",
      color: "Gris",
      licensePlate: "AB 123 CD",
    },
    origin: {
      address: "Av. del Libertador 7200, Núñez",
      lat: -34.5447,
      lng: -58.4584,
    },
    destination: {
      address: "UTDT - Sede Alcorta, Av. Figueroa Alcorta 7350",
      lat: -34.5426,
      lng: -58.4637,
    },
    date: "2026-03-30",
    departureTime: "08:30",
    totalSeats: 3,
    availableSeats: 2,
    pickupFlexibility: "flexible",
    flexibleRadiusKm: 1.5,
    vibe: { music: true, chat: true, quiet: false },
    note: "Paso por Belgrano R, tengo espacio en el baúl",
    status: "active",
    passengers: [],
    ratings: [],
    createdAt: now,
  },
  {
    id: "ride2",
    driverId: "user2",
    driverName: "Tomi López",
    driverPhotoUrl: "/avatars/tomi.jpg",
    driverDepartment: "Negocios Digitales",
    driverRating: 4.6,
    driverCar: {
      brand: "Chevrolet",
      model: "Onix",
      color: "Blanco",
      licensePlate: "EF 456 GH",
    },
    origin: {
      address: "Av. Cabildo 1500, Belgrano",
      lat: -34.5617,
      lng: -58.4535,
    },
    destination: {
      address: "UTDT - Sede Alcorta, Av. Figueroa Alcorta 7350",
      lat: -34.5426,
      lng: -58.4637,
    },
    date: "2026-03-30",
    departureTime: "09:00",
    totalSeats: 2,
    availableSeats: 2,
    pickupFlexibility: "fixed",
    vibe: { music: false, chat: true, quiet: false },
    status: "active",
    passengers: [],
    ratings: [],
    createdAt: now,
  },
  {
    id: "ride3",
    driverId: "user6",
    driverName: "Sofi Fernández",
    driverPhotoUrl: "/avatars/demo2.jpg",
    driverDepartment: "MBA",
    driverRating: 4.7,
    driverCar: {
      brand: "VW",
      model: "Golf",
      color: "Negro",
      licensePlate: "IJ 789 KL",
    },
    origin: {
      address: "Av. Centenario 500, San Isidro",
      lat: -34.4711,
      lng: -58.5125,
    },
    destination: {
      address: "UTDT - Sede Alcorta, Av. Figueroa Alcorta 7350",
      lat: -34.5426,
      lng: -58.4637,
    },
    date: "2026-03-30",
    departureTime: "08:00",
    totalSeats: 3,
    availableSeats: 3,
    pickupFlexibility: "flexible",
    flexibleRadiusKm: 2.0,
    vibe: { music: false, chat: false, quiet: true },
    note: "Viaje tranqui, salgo temprano",
    status: "active",
    passengers: [],
    ratings: [],
    createdAt: now,
  },
];
