import { User, Ride } from "@/types";
import { Timestamp } from "firebase/firestore";

const now = Timestamp.now();

export const MOCK_USERS: User[] = [
  {
    id: "user1",
    email: "nico@unc.edu",
    name: "Nico Garcia",
    photoUrl: "/avatars/nico.jpg",
    department: "Business Administration",
    neighborhood: "Chapel Hill",
    interests: ["fintech", "soccer", "entrepreneurship"],
    car: {
      brand: "Toyota",
      model: "Corolla",
      color: "Gray",
      licensePlate: "ABC-1234",
    },
    stats: {
      totalRides: 24,
      totalKm: 312,
      co2Saved: 65.5,
      peopleConnected: 8,
      averageRating: 4.8,
      averageBuenaOnda: 4.6,
      totalRatings: 18,
    },
    badges: [
      {
        id: "icebreaker",
        name: "Icebreaker",
        description: "First ride with someone new",
        icon: "🧊",
        unlockedAt: now,
      },
      {
        id: "eco-hero",
        name: "Eco Hero",
        description: "Saved over 50 kg of CO2",
        icon: "🌱",
        unlockedAt: now,
      },
      {
        id: "punctual",
        name: "Punctual",
        description: "Always on time",
        icon: "⏰",
        unlockedAt: now,
      },
    ],
    connections: ["user2", "user3"],
    createdAt: now,
  },
  {
    id: "user2",
    email: "tomi@unc.edu",
    name: "Tomi Lopez",
    photoUrl: "/avatars/tomi.jpg",
    department: "Computer Science",
    neighborhood: "Carrboro",
    interests: ["technology", "running", "movies"],
    car: {
      brand: "Chevrolet",
      model: "Malibu",
      color: "White",
      licensePlate: "DEF-5678",
    },
    stats: {
      totalRides: 15,
      totalKm: 180,
      co2Saved: 37.8,
      peopleConnected: 5,
      averageRating: 4.6,
      averageBuenaOnda: 4.3,
      totalRatings: 12,
    },
    badges: [
      {
        id: "icebreaker",
        name: "Icebreaker",
        description: "First ride with someone new",
        icon: "🧊",
        unlockedAt: now,
      },
    ],
    connections: ["user1", "user3"],
    createdAt: now,
  },
  {
    id: "user3",
    email: "belu@unc.edu",
    name: "Belu Martinez",
    photoUrl: "/avatars/belu.jpg",
    department: "Economics",
    neighborhood: "Durham",
    interests: ["yoga", "travel", "reading"],
    stats: {
      totalRides: 10,
      totalKm: 95,
      co2Saved: 19.9,
      peopleConnected: 4,
      averageRating: 4.9,
      averageBuenaOnda: 4.8,
      totalRatings: 8,
    },
    badges: [
      {
        id: "icebreaker",
        name: "Icebreaker",
        description: "First ride with someone new",
        icon: "🧊",
        unlockedAt: now,
      },
      {
        id: "explorer",
        name: "Explorer",
        description: "Rode with people from 5 different departments",
        icon: "🧭",
        unlockedAt: now,
      },
    ],
    connections: ["user1", "user2"],
    createdAt: now,
  },
  {
    id: "user4",
    email: "flor@unc.edu",
    name: "Flor Russo",
    photoUrl: "/avatars/flor.jpg",
    department: "Design",
    neighborhood: "Hillsborough",
    interests: ["art", "music", "photography"],
    stats: {
      totalRides: 6,
      totalKm: 42,
      co2Saved: 8.8,
      peopleConnected: 3,
      averageRating: 5.0,
      averageBuenaOnda: 4.9,
      totalRatings: 5,
    },
    badges: [],
    connections: [],
    createdAt: now,
  },
  {
    id: "user5",
    email: "demo@unc.edu",
    name: "Martin Perez",
    photoUrl: "/avatars/demo.jpg",
    department: "Political Science",
    neighborhood: "Raleigh",
    interests: ["soccer", "politics"],
    stats: {
      totalRides: 0,
      totalKm: 0,
      co2Saved: 0,
      peopleConnected: 0,
      averageRating: 0,
      averageBuenaOnda: 0,
      totalRatings: 0,
    },
    badges: [],
    connections: [],
    createdAt: now,
  },
  {
    id: "user6",
    email: "sofi@unc.edu",
    name: "Sofi Fernandez",
    photoUrl: "/avatars/demo2.jpg",
    department: "Business Administration",
    neighborhood: "Durham",
    interests: ["fintech", "startups"],
    car: {
      brand: "VW",
      model: "Golf",
      color: "Black",
      licensePlate: "GHI-9012",
    },
    stats: {
      totalRides: 18,
      totalKm: 290,
      co2Saved: 60.9,
      peopleConnected: 7,
      averageRating: 4.7,
      averageBuenaOnda: 4.5,
      totalRatings: 14,
    },
    badges: [
      {
        id: "icebreaker",
        name: "Icebreaker",
        description: "First ride with someone new",
        icon: "🧊",
        unlockedAt: now,
      },
      {
        id: "eco-hero",
        name: "Eco Hero",
        description: "Saved over 50 kg of CO2",
        icon: "🌱",
        unlockedAt: now,
      },
    ],
    connections: ["user1"],
    createdAt: now,
  },
];

export const MOCK_RIDES: Ride[] = [
  {
    id: "ride1",
    driverId: "user1",
    driverName: "Nico Garcia",
    driverPhotoUrl: "/avatars/nico.jpg",
    driverDepartment: "Business Administration",
    driverRating: 4.8,
    driverCar: {
      brand: "Toyota",
      model: "Corolla",
      color: "Gray",
      licensePlate: "ABC-1234",
    },
    origin: {
      address: "210 Henderson St, Chapel Hill, NC",
      lat: 35.9132,
      lng: -79.0558,
    },
    destination: {
      address: "UNC Chapel Hill, South Rd, Chapel Hill, NC",
      lat: 35.9049,
      lng: -79.0469,
    },
    date: "2026-03-30",
    departureTime: "08:30",
    totalSeats: 3,
    availableSeats: 2,
    pickupFlexibility: "flexible",
    flexibleRadiusKm: 2.4,
    vibe: { music: true, chat: true, quiet: false },
    note: "Driving through Carrboro, trunk space available",
    status: "active",
    passengers: [],
    ratings: [],
    createdAt: now,
  },
  {
    id: "ride2",
    driverId: "user2",
    driverName: "Tomi Lopez",
    driverPhotoUrl: "/avatars/tomi.jpg",
    driverDepartment: "Computer Science",
    driverRating: 4.6,
    driverCar: {
      brand: "Chevrolet",
      model: "Malibu",
      color: "White",
      licensePlate: "DEF-5678",
    },
    origin: {
      address: "300 E Main St, Carrboro, NC",
      lat: 35.9101,
      lng: -79.0753,
    },
    destination: {
      address: "UNC Chapel Hill, South Rd, Chapel Hill, NC",
      lat: 35.9049,
      lng: -79.0469,
    },
    date: "2026-03-30",
    departureTime: "09:00",
    totalSeats: 2,
    availableSeats: 2,
    pickupFlexibility: "fixed",
    vibe: { music: false, chat: true, quiet: false },
    status: "active",
    passengers: [],
    ratings: [],
    createdAt: now,
  },
  {
    id: "ride3",
    driverId: "user6",
    driverName: "Sofi Fernandez",
    driverPhotoUrl: "/avatars/demo2.jpg",
    driverDepartment: "Business Administration",
    driverRating: 4.7,
    driverCar: {
      brand: "VW",
      model: "Golf",
      color: "Black",
      licensePlate: "GHI-9012",
    },
    origin: {
      address: "800 W Main St, Durham, NC",
      lat: 35.9940,
      lng: -78.9106,
    },
    destination: {
      address: "UNC Chapel Hill, South Rd, Chapel Hill, NC",
      lat: 35.9049,
      lng: -79.0469,
    },
    date: "2026-03-30",
    departureTime: "08:00",
    totalSeats: 3,
    availableSeats: 3,
    pickupFlexibility: "flexible",
    flexibleRadiusKm: 3.2,
    vibe: { music: false, chat: false, quiet: true },
    note: "Quiet ride, leaving early",
    status: "active",
    passengers: [],
    ratings: [],
    createdAt: now,
  },
];
